create table public.usuarios (
  id bigint generated by default as identity not null,
  cedula character varying(20) not null,
  contraseña character varying(255) not null,
  constraint usuarios_pkey primary key (id),
  constraint usuarios_cedula_key unique (cedula)
) TABLESPACE pg_default;